version: '3'
services:
  app:
    container_name: docker-node-mongo
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
